### ISSUE TITLE
Crash server when join guild

### ISSUE THREAD

**Issue by Tsugami** [Invasor-de-Fronteiras/Kelbi#41]
https://github.com/Invasor-de-Fronteiras/Kelbi/blob/71c2476e859e8a7436a20a5dc1a11ba2b4b5c726/server/channelserver/handlers_guild.go#L1059

```sh
poboru-channels    | panic: runtime error: invalid memory address or nil pointer dereference
poboru-channels    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x8bc46d]
poboru-channels    |
poboru-channels    | goroutine 203 [running]:
poboru-channels    | erupe-ce/server/channelserver.handleMsgMhfInfoGuild(0xc00024a700, 0xc98438, 0xc0004da0f0)
poboru-channels    |    /app/server/channelserver/handlers_guild.go:1057 +0xbed
poboru-channels    | erupe-ce/server/channelserver.(*Session).handlePacketGroup(0xc00024a700, 0xc0004da0d0, 0xc, 0x10)
poboru-channels    |    /app/server/channelserver/sys_session.go:228 +0x216
poboru-channels    | erupe-ce/server/channelserver.(*Session).recvLoop(0xc00024a700)
poboru-channels    |    /app/server/channelserver/sys_session.go:191 +0x54
poboru-channels    | erupe-ce/server/channelserver.(*Session).Start.func1(0xc00024a700)
poboru-channels    |    /app/server/channelserver/sys_session.go:100 +0x1a5
poboru-channels    | created by erupe-ce/server/channelserver.(*Session).Start
poboru-channels    |    /app/server/channelserver/sys_session.go:95 +0x3f
```

**Comment by Malckyor** [comment]
"Perhaps" this can fix it:
https://github.com/ZeruLight/Erupe/commit/e38c8926140d73545e05761f37d2cc6b6d6bcffb

**Comment by Tsugami** [comment]
Done! https://github.com/Invasor-de-Fronteiras/Kelbi/commit/9cf1fe961a6b49872d2403561c96af1b9563fabe
